//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuegoSolitario.ServicioSolitario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioSolitario.IServicioSolitario")]
    public interface IServicioSolitario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSolitario/RepartirCartas", ReplyAction="http://tempuri.org/IServicioSolitario/RepartirCartasResponse")]
        int[] RepartirCartas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSolitario/RepartirCartas", ReplyAction="http://tempuri.org/IServicioSolitario/RepartirCartasResponse")]
        System.Threading.Tasks.Task<int[]> RepartirCartasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSolitario/MovimientoColumnas", ReplyAction="http://tempuri.org/IServicioSolitario/MovimientoColumnasResponse")]
        bool MovimientoColumnas(string colorCartaSalida, int numeroCartaSalida, string colorCartaLlegada, int numeroCartaLlegada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSolitario/MovimientoColumnas", ReplyAction="http://tempuri.org/IServicioSolitario/MovimientoColumnasResponse")]
        System.Threading.Tasks.Task<bool> MovimientoColumnasAsync(string colorCartaSalida, int numeroCartaSalida, string colorCartaLlegada, int numeroCartaLlegada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSolitario/MovimientoFinal", ReplyAction="http://tempuri.org/IServicioSolitario/MovimientoFinalResponse")]
        bool MovimientoFinal(string paloCartaSalida, int numeroCartaSalida, string paloCartaLlegada, int numeroCartaLlegada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSolitario/MovimientoFinal", ReplyAction="http://tempuri.org/IServicioSolitario/MovimientoFinalResponse")]
        System.Threading.Tasks.Task<bool> MovimientoFinalAsync(string paloCartaSalida, int numeroCartaSalida, string paloCartaLlegada, int numeroCartaLlegada);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioSolitarioChannel : JuegoSolitario.ServicioSolitario.IServicioSolitario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioSolitarioClient : System.ServiceModel.ClientBase<JuegoSolitario.ServicioSolitario.IServicioSolitario>, JuegoSolitario.ServicioSolitario.IServicioSolitario {
        
        public ServicioSolitarioClient() {
        }
        
        public ServicioSolitarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioSolitarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSolitarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSolitarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int[] RepartirCartas() {
            return base.Channel.RepartirCartas();
        }
        
        public System.Threading.Tasks.Task<int[]> RepartirCartasAsync() {
            return base.Channel.RepartirCartasAsync();
        }
        
        public bool MovimientoColumnas(string colorCartaSalida, int numeroCartaSalida, string colorCartaLlegada, int numeroCartaLlegada) {
            return base.Channel.MovimientoColumnas(colorCartaSalida, numeroCartaSalida, colorCartaLlegada, numeroCartaLlegada);
        }
        
        public System.Threading.Tasks.Task<bool> MovimientoColumnasAsync(string colorCartaSalida, int numeroCartaSalida, string colorCartaLlegada, int numeroCartaLlegada) {
            return base.Channel.MovimientoColumnasAsync(colorCartaSalida, numeroCartaSalida, colorCartaLlegada, numeroCartaLlegada);
        }
        
        public bool MovimientoFinal(string paloCartaSalida, int numeroCartaSalida, string paloCartaLlegada, int numeroCartaLlegada) {
            return base.Channel.MovimientoFinal(paloCartaSalida, numeroCartaSalida, paloCartaLlegada, numeroCartaLlegada);
        }
        
        public System.Threading.Tasks.Task<bool> MovimientoFinalAsync(string paloCartaSalida, int numeroCartaSalida, string paloCartaLlegada, int numeroCartaLlegada) {
            return base.Channel.MovimientoFinalAsync(paloCartaSalida, numeroCartaSalida, paloCartaLlegada, numeroCartaLlegada);
        }
    }
}
